## Updated the https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml
## 1. No Reverse proxy using NGNIX, so added the -ports to alfresco and share
## 2. Both alfresco and share are running at 8080, so making alfresco run on 8080 and share on 8081
## 3. Error with dir.root, Set dir.root to an absolute path inside the container (ERROR - System content not found in content store: 'store://2024/9/19/13/47/d9a2f6ff-031e-4000-a2f6-ff031ee00061.bin)

version: '3.9'

services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:23.3.0
    mem_limit: 1900m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.http.connection.timeout=1000
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=127.0.0.1
        -Dshare.port=8081
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dcsrf.filter.enabled=false
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Ddir.root=/usr/local/tomcat/alf_data
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    ports:
      - "8080:8080"  # Expose Alfresco on port 8080 to the host
    volumes:
      - ./alf_data:/usr/local/tomcat/alf_data  # Map alf_data directory to the host for persistence

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.1.4
    mem_limit: 1536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    ports:
      - "8090:8090"
    volumes:
      - ./alf_data:/usr/local/tomcat/alf_data  # Map alf_data directory to the host for persistence

  share:
    image: alfresco/alfresco-share:23.3.0
    mem_limit: 1g
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
    ports:
      - "8081:8080"  # Expose Share on port 8081 to the host, but still use port 8080 internally

  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      POSTGRES_PASSWORD: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_DB: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"

  solr6:
    image: alfresco/alfresco-search-services:2.0.11
    mem_limit: 2g
    environment:
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "8083:8983"  # Browser port

  activemq:
    image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
    mem_limit: 1g
    ports:
      - "8161:8161"  # Web Console
      - "5672:5672"  # AMQP
      - "61616:61616"  # OpenWire
      - "61613:61613"  # STOMP
