version: '3.9'
services:
  alfresco:
    build:
      context: ./alfresco                         
      dockerfile: Dockerfile                 
      args:
        ALFRESCO_TAG: ${ALFRESCO_VERSION}
    mem_limit: 1900m
    depends_on:                     # Add depends on DB
      - postgres
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.http.connection.timeout=1000
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=localhost
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dcsrf.filter.enabled=false
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80

  # Added custom Log path and logger levels
  transform-core-aio:
    build:
      context: ./ats                           # ATS path where the Dockerfile is
      dockerfile: Dockerfile
    mem_limit: 1536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Djava.io.tmpdir=/tmp/custom-ats-temp
        -Dlogging.level.org.alfresco.transform.common.TransformerDebug=ERROR
        -Dlogging.level.org.alfresco.transform=ERROR
        -Dlogging.level.org.apache.fontbox.ttf=ERROR
        -Dlogging.level.org.apache.pdfbox.cos.COSDocument=ERROR
        -Dlogging.level.org.apache.pdfbox.pdfparser=ERROR
        -Dlogging.level.org.apache.pdfbox.filter.FlateFilter=ERROR
        -Dlogging.level.org.apache.pdfbox.pdmodel.font=ERROR
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDSimpleFont=FATAL
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDFont=FATAL
        -Dlogging.level.org.apache.pdfbox.pdmodel.font.PDCIDFont=FATAL
    ports:
      - "8090:8090"
    volumes:
      - ats-temp:/tmp/custom-ats-temp               # Map the custom ATS temp directory

  share:
    build:
      context: ./share                           
      dockerfile: Dockerfile                   
      args:
        SHARE_TAG: ${SHARE_VERSION}
    mem_limit: 1g
    environment:
      CSRF_FILTER_REFERER: "http://localhost(:[0-9]*)?/.*"
      CSRF_FILTER_ORIGIN: "http://localhost:8080"
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http

  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"

  solr6:
    image: docker.io/alfresco/alfresco-search-services:2.0.11
    mem_limit: 2g
    environment:
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "8083:8983" # Browser port

  activemq:
    image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
    mem_limit: 1g
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    mem_limit: 128m
    depends_on:
      - alfresco
    ports:
      - "8080:8080"

# Define the custom volume for the ats-temp directory
volumes:
  ats-temp:
