version: '3.9'

services:
 activemq:
    image: alfresco/alfresco-activemq:${ACTIVEMQ_VERSION} 
    mem_limit: 1g
    ports:
      - "8161:8161"   # Web Console
      - "5672:5672"   # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP
