version: '3.9'

services:
  transform-core-aio:
    #image: alfresco/alfresco-transform-core-aio:5.1.4 (we are making modifications to original one)
    build:
      context: .
      dockerfile: Dockerfile                   # Make sure this matches the name of your Dockerfile, (you can also build image seperatly and provide image: custom-transform-core-aio:latest, no dockerfile tag)
    mem_limit: 1536m
    environment:                               # adding the custom temporary file directory for Java using -Djava.io.tmpdir=/tmp/custom
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Djava.io.tmpdir=/tmp/custom        
    volumes:
      - temp_volume:/tmp/custom               # Map the temp_volume to the custom temp directory inside the container
    ports:
      - "8090:8090"

# Define the custom volume for the temp directory
volumes:
  temp_volume:
