FROM alfresco/alfresco-transform-core-aio:5.1.4

# Create the temp directory and set the appropriate permissions (combine to save image size)
RUN mkdir -p /tmp/custom-ats-temp && chmod 1777 /tmp/custom-ats-temp
